### ISSUE TITLE
 File "blockchain.py", line 4, in <module>     from urlparse import urlparse

### ISSUE THREAD

**Issue by theparadoxer02** [satwikkansal/YourNet#8]
```
 File "blockchain.py", line 4, in <module>
    from urlparse import sparse
```
**Note:-** _The urlparse module is renamed to urllib.parse in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3._

**Source** :- https://docs.python.org/2/library/urlparse.html

**Comment by theparadoxer02** [comment]
Here is the fix https://github.com/satwikkansal/YourNet/pull/9

**Comment by satwikkansal** [comment]
Merged, thanks :)
